import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const OUT_DIR = path.join(ROOT, 'public', 'frames')
const GEN_DIR = path.join(ROOT, 'src', 'generated')

const PACK = 'jonnyjackson26/device-frames-media'
const BRANCH = 'main'
const INDEX_URL = `https://raw.githubusercontent.com/${PACK}/${BRANCH}/device-frames-output/index.json`

function titleCase(s) {
  return s
    .split('-')
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ')
}

function slugify(s) {
  return s
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

async function download(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`)
  return Buffer.from(await res.arrayBuffer())
}

async function ensureDirs(relPath) {
  await mkdir(path.join(OUT_DIR, relPath), { recursive: true })
}

function templateUrlFromFrame(frameUrl) {
  return frameUrl.replace(/\/[^/]*$/, '/template.json')
}

async function main() {
  const res = await fetch(INDEX_URL)
  if (!res.ok) throw new Error(`Failed to fetch index: ${res.status}`)
  const index = await res.json()

  const groups = []
  let total = 0

  for (const [catKey, catVal] of Object.entries(index)) {
    const models = []
    for (const [modelKey, modelVal] of Object.entries(catVal)) {
      const variants = []
      for (const [variantKey, variantVal] of Object.entries(modelVal)) {
        const rel = path.join(catKey, slugify(modelKey), slugify(variantKey))

        await ensureDirs(rel)
        const tasks = [
          [variantVal.frame, path.join(rel, 'frame.png')],
          [variantVal.mask, path.join(rel, 'mask.png')],
          [templateUrlFromFrame(variantVal.frame), path.join(rel, 'template.json')],
        ]

        for (const [url, dest] of tasks) {
          const buf = await download(url)
          await writeFile(path.join(OUT_DIR, dest), buf)
        }

        const tpl = JSON.parse(
          (await readFile(path.join(OUT_DIR, rel, 'template.json'))).toString()
        )

        variants.push({
          key: `${slugify(modelKey)}-${slugify(variantKey)}`,
          modelKey: slugify(modelKey),
          groupKey: catKey,
          label: titleCase(variantKey),
          frame: `frames/${rel}/frame.png`,
          mask: `frames/${rel}/mask.png`,
          hexColor: tpl.hexColor ?? null,
          screen: tpl.screen,
          frameSize: tpl.frameSize,
        })
        total++
      }
      models.push({
        key: slugify(modelKey),
        label: titleCase(modelKey),
        variants,
      })
    }
    groups.push({
      key: catKey,
      label: {
        'apple-iphone': 'Apple iPhone',
        'apple-ipad': 'Apple iPad',
        'android-phone': 'Android Phone',
        'android-tablet': 'Android Tablet',
      }[catKey] ?? titleCase(catKey),
      models,
    })
  }

  await mkdir(GEN_DIR, { recursive: true })
  const catalogSrc = `// AUTO-GENERATED by scripts/fetch-frames.mjs — do not edit.
// Frame artwork: open-source device-frames-media pack by jonnyjackson26.
export interface FrameScreen { x: number; y: number; width: number; height: number }
export interface FrameSize { width: number; height: number }
export interface FrameVariant {
  key: string
  modelKey: string
  groupKey: string
  label: string
  frame: string
  mask: string
  hexColor: string | null
  screen: FrameScreen
  frameSize: FrameSize
}
export interface FrameModel {
  key: string
  label: string
  variants: FrameVariant[]
}
export interface FrameGroup {
  key: string
  label: string
  models: FrameModel[]
}

export const FRAME_GROUPS: FrameGroup[] = ${JSON.stringify(groups, null, 2)}
`

  await writeFile(path.join(GEN_DIR, 'frames-catalog.ts'), catalogSrc)
  console.log(`\nDone. Downloaded ${total} variants into ${path.relative(ROOT, OUT_DIR)}`)
  console.log(`Catalog written to ${path.relative(ROOT, path.join(GEN_DIR, 'frames-catalog.ts'))}`)
  console.log(`Total download size: ~${(total * 0.2).toFixed(0)} MB (estimated)`)

  const sharp = (await import('sharp')).default
  await sharp({
    create: { width: 1200, height: 630, channels: 4, background: '#141633' },
  })
    .composite([
      {
        input: Buffer.from(
          `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
            <rect width="1200" height="630" fill="#141633"/>
            <rect x="150" y="95" width="900" height="440" rx="28" fill="none" stroke="#8b93ff" stroke-width="4"/>
            <rect x="200" y="150" width="620" height="330" rx="14" fill="#8b93ff" opacity="0.85"/>
            <text x="240" y="640" font-family="Arial" font-size="14" fill="#8b93ff">device-frames-media by @jonnyjackson26</text>
          </svg>`
        ),
      },
    ])
    .png()
    .toFile(path.join(ROOT, 'public', 'og-image.png'))
  console.log('og-image.png written')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})